### ISSUE TITLE
Add queue and pending

### ISSUE THREAD

**Issue by uzerus** [ludios/grab-site#103]
pending is not important as queue

maybe we can set max jobs of grab-site and add a list of websites to crawl after that jobs are finished?

sorry for bad english

**Comment by ivan** [comment]
I don't think this should be in grab-site, but it's possible to do with external queuing tools.

I have sometimes used a for loop, e.g.:

```
for i in site1 site2 site3; do grab-site $i; done
```

Or, if you want to dynamically queue things, I have used [Task Spooler](http://vicerveza.homeunix.net/~viric/soft/ts/) before to some success (in Debian/Ubuntu, package `task-spooler`, command `tsp`.)
