### ISSUE TITLE
Add a default get_urls hook to get :orig quality images on Twitter

### ISSUE THREAD

**Issue by ivan** [ludios/grab-site#107]
Are there any other obvious URLs to additionally queue when we see certain URLs on various websites?  Suggestions welcome.

**Comment by brandongalbraith** [comment]
[Flickr](https://www.flickr.com/services/api/misc.urls.html)

**Comment by brandongalbraith** [comment]
[Quora](https://www.google.com/search?q=quora+share%3D1) (add `?share=1` to end of URL to prevent the need to login to retrieve content)

**Comment by ivan** [comment]
[tumblr images](https://github.com/ludios/original-quality-images/blob/b60918dac2c93c87d3db8a8779d02a5905c69fd5/background.js#L24-L25) too

**Comment by ethus3h** [comment]
This seems similar to https://github.com/ludios/grab-site/issues/88 to me...

**Comment by ivan** [comment]
I tried implementing this in branch [get-urls-hook](https://github.com/ludios/grab-site/tree/get-urls-hook), but when wpull gets to the `:orig` URL in the queue, it just puts it into the skipped state, for reasons unknown to me.

**Comment by ivan** [comment]
URLs were getting skipped because of grab-site's `--no-parent` combined with the lack of `inline=True` in the hook.

Implemented for Twitter and Quora in 0ea3d4093860ac526ea5e2d8c591ea31df3ccd44.

I didn't want to deal with Flickr (it looks like it uses a different secret for the original image anyway), but I would take a PR for it (to get the largest non-original image?).

**Comment by brandongalbraith** [comment]
Thank you @ivan! 👏👏👏
