### ISSUE TITLE
Add archive.org to global ignore set

### ISSUE THREAD

**Issue by brandongalbraith** [ludios/grab-site#118]

**Comment by ivan** [comment]
I've thought about doing this, but it doesn't always make sense, because someone might be trying to capture Wayback before some domain gets robots.txt'ed.

I would recommend using the new `--import-ignores` and aliasing `grab-site` to include the argument.

**Comment by brandongalbraith** [comment]
Got it! Thanks @ivan! I ran into a site that happened to reference fairly large items on archive.org while I wasn't monitoring my crawl. I'll update my personal import ignores locally.

**Comment by ivan** [comment]
(I guess I was talking about web.archive.org, but it sort of applies to archive.org items as well - they sometimes get darked.)

**Comment by brandongalbraith** [comment]
My crawls are for WayBack machine ingest :)

**Comment by jodizzle** [comment]
Would it be appropriate to have some other igset in the `ignore_sets` folder for various archival site links?  It seems like it would be generally useful.
