### ISSUE TITLE
Cannot get gs-server to start

### ISSUE THREAD

**Issue by brentoage** [ludios/grab-site#122]
I followed the instructions for installing on OS X - everything appears to have installed properly. Configuration appears sound, ~/.bash_profile has been updated. But... gs-server will not launch. Receiving this message: **command not found: gs-server**. 

So... it would appear that I have missed a step or something is missing. I'm completely new to this, any help would be appreciated. I'm not sure how to begin debugging. Thanks!

**Comment by ivan** [comment]
@brentoage please let me know if starting a new shell/terminal did not fix the issue and I'll reopen
