### ISSUE TITLE
grab-site does not check directory name length before attempting to create, making it fail

### ISSUE THREAD

**Issue by ethus3h** [ludios/grab-site#15]
grab-site is unable to fetch long URLs, exiting with an error from mkdir:

`grab-site http://search.4shared.com/q/1/%EF%93%AF%E2%A0%80%E5%83%8E%EB%94%84%EF%8D%97%ED%99%B8%EA%8D%95%E9%B8%A2%EB%97%AB%E1%8C%8B%ED%90%8B%EF%BF%BD%E9%8B%BB%EB%8C%80%CA%80%E5%8E%AD%E6%85%9F%E5%8E%82%E5%81%A8%E0%AD%AB%E3%83%AC%E6%B6%AA%EA%84%8A%E7%9D%A3%E9%96%87%E8%85%8D%EA%B1%94%E7%81%AF%EA%A7%B3%E7%AE%B4%EE%8F%B1%E8%A2%8A%EA%96%AF%E5%82%9F%EE%9A%A2%E5%AE%80%E0%B9%86%EC%89%8D%EB%A9%BE%E3%9A%B6%EF%BF%BD%EF%BF%BD%E8%B2%BA%EB%A1%BC%EE%83%BC%E5%8B%8B%E3%A9%8D%E7%97%87%EF%94%BB%CB%BA%E6%A6%8B%EA%9E%8F%EB%96%BD%E8%97%88%E6%AA%A8%E7%A0%AF%E9%BF%8C%EA%B6%8E%E6%AF%94%E1%93%A3%E4%9B%9F%EE%B9%8B%E3%92%A9%E6%91%BA%ED%92%94%EA%B6%A2%E5%A7%A4%EC%86%8C%EE%BD%B2%EA%BB%AA%E6%95%B1%EE%B9%8D%E1%BD%8F%E7%A1%9C%EA%AB%A9%E1%B5%BD%EE%BA%9D%E2%AC%94%E8%81%87?locale=en --1
mkdir: search.4shared.com-q-1-%EF%93%AF%E2%A0%80%E5%83%8E%EB%94%84%EF%8D%97%ED%99%B8%EA%8D%95%E9%B8%A2%EB%97%AB%E1%8C%8B%ED%90%8B%EF%BF%BD%E9%8B%BB%EB%8C%80%CA%80%E5%8E%AD%E6%85%9F%E5%8E%82%E5%81%A8%E0%AD%AB%E3%83%AC%E6%B6%AA%EA%84%8A%E7%9D%A3%E9%96%87%E8%85%8D%EA%B1%94%E7%81%AF%EA%A7%B3%E7%AE%B4%EE%8F%B1%E8%A2%8A%EA%96%AF%E5%82%9F%EE%9A%A2%E5%AE%80%E0%B9%86%EC%89%8D%EB%A9%BE%E3%9A%B6%EF%BF%BD%EF%BF%BD%E8%B2%BA%EB%A1%BC%EE%83%BC%E5%8B%8B%E3%A9%8D%E7%97%87%EF%94%BB%CB%BA%E6%A6%8B%EA%9E%8F%EB%96%BD%E8%97%88%E6%AA%A8%E7%A0%AF%E9%BF%8C%EA%B6%8E%E6%AF%94%E1%93%A3%E4%9B%9F%EE%B9%8B%E3%92%A9%E6%91%BA%ED%92%94%EA%B6%A2%E5%A7%A4%EC%86%8C%EE%BD%B2%EA%BB%AA%E6%95%B1%EE%B9%8D%E1%BD%8F%E7%A1%9C%EA%AB%A9%E1%B5%BD%EE%BA%9D%E2%AC%94%E8%81%87-locale=en-2015-07-27-ebb7430e: File name too long`

**Comment by ivan** [comment]
This should be fixed as of 37d1f2e4733e325a401e4370b419b992224e4e8c
