### ISSUE TITLE
How to peek into URL queue?

### ISSUE THREAD

**Issue by ethus3h** [ludios/grab-site#19]
This isn't necessarily an issue as such as a question since I can't find a better way to post "support questions", but is there a way to look at the URL queue in advance and see what is going to be coming up so I can add ignores if necessary ahead of time (e.g. before going to bed)? Thanks! :)

**Comment by ivan** [comment]
Please give the new `gs-dump-urls` a try!  It is documented in the README and in its `--help` info.

Support questions are fine here.

**Comment by ethus3h** [comment]
Sweetness, thanks! :D
