### ISSUE TITLE
It crashed and burned, for me. OS X 10.10.3 :)

### ISSUE THREAD

**Issue by ethus3h** [ludios/grab-site#2]
$ ./grab-site https://github.com/ludios/grab-site
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
mkdir: illegal option -- 2
usage: mkdir [-pv] [-m mode] directory ...
$

**Comment by ivan** [comment]
Thanks for trying this out.  What's your OS and what does `sed --version` say?

**Comment by ivan** [comment]
Oh, right, OS X, I'll try to make it work soon.

**Comment by ivan** [comment]
Can you tell me which Python 3 you're using on OS X, just so that I can get it working on that platform first?  (installer from python.org? macports?)

**Comment by ethus3h** [comment]
python3 --version gives:
Python 3.4.2

which python3 gives:
/usr/local/bin/python3

I suspect I would be using macports, but I istalled it a long time ago and don't remmeber. I do use macprots for most things though

**Comment by ethus3h** [comment]
Thanks for looking at it!
:)

**Comment by ivan** [comment]
I added some OS X support, but only tested with the python.org installer.  Please give the latest grab-site a try and let me know if it works with your Python.

**Comment by ivan** [comment]
Issue submitter reports this is now working

**Comment by ethus3h** [comment]
Thanks! :)
