### ISSUE TITLE
Add -i / --input-file option to feed in URLs

### ISSUE THREAD

**Issue by ethus3h** [ludios/grab-site#22]
Add an `--input-file` option, which should cover the ArchiveBot `!a < URL` and  `!ao < URL` functionality, which loads URLs from `URL`.

(Bug description replaced -ivan)

**Comment by ivan** [comment]
Implemented as of 668c03d5d2f9e76e44bda505206f2aabd9cce3f2, please upgrade and give it a try

**Comment by ethus3h** [comment]
Ah! Glad to see this is fixed, this will be very useful. Haven't tested yet though. Thanks! :)
