### ISSUE TITLE
Add option to output responses to files on disk

### ISSUE THREAD

**Issue by ethus3h** [ludios/grab-site#24]
Add support for writing HTTP/FTP responses to disk as one file per response, which would provide functionality similar and wget or HTTrack.

(Bug description replaced -ivan)

**Comment by ivan** [comment]
Extension adding/renaming would have to be handled by wpull, does it do that?

**Comment by ivan** [comment]
It is tempting to make this Not My Problem and point users to https://github.com/chfoo/warcat for extracting .warc.gz files.  That has the advantage of being able to re-extract files from the WARC file if you didn't like the output.  (After fixing warcat or or changing its options.)  If these files were dumped by grab-site instead, users would have to re-crawl the site.

**Comment by ivan** [comment]
or https://github.com/recrm/ArchiveTools/wiki/warc-extractor

**Comment by ethus3h** [comment]
Hmm,true. I'll have to look into whether wpull shares that feature with wget

**Comment by ivan** [comment]
Closed in favor of #39
