### ISSUE TITLE
gs-server raises KeyError with Firefox 42 client on OS X

### ISSUE THREAD

**Issue by ethus3h** [ludios/grab-site#53]
Getting this error on a server that has been working before. I can open the dashboard, but jobs don't show up...

tcp:127.0.0.1:58617 connected
tcp:127.0.0.1:58617 is grabbing http://[example].com/
tcp:72.65.99.136:62506 disconnected
Exception in callback _SelectorTransport._call_connection_lost(None)
handle: <Handle _SelectorTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 609, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/home/gsserver/.local/lib/python3.4/site-packages/autobahn/asyncio/websocket.py", line 96, in connection_lost
    self._connectionLost(exc)
  File "/home/gsserver/.local/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 2758, in _connectionLost
    WebSocketProtocol._connectionLost(self, reason)
  File "/home/gsserver/.local/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 1245, in _connectionLost
    self._onClose(self.wasClean, WebSocketProtocol.CLOSE_STATUS_CODE_ABNORMAL_CLOSE, "connection was closed uncleanly (%s)" % self.wasNotCleanReason)
  File "/home/gsserver/.local/lib/python3.4/site-packages/autobahn/asyncio/websocket.py", line 173, in _onClose
    res = self.onClose(wasClean, code, reason)
  File "/home/gsserver/.local/lib/python3.4/site-packages/libgrabsite/server.py", line 24, in onClose
    self.factory.clients.remove(self)
KeyError: <libgrabsite.server.GrabberServerProtocol object at 0x7fd0eae65f28>

**Comment by ivan** [comment]
This is definitely a bug in gs-server (or a dependency), even if you were doing something weird.  I'll take a look.  Any idea how you might have gotten it into this state?

**Comment by ivan** [comment]
Was this on Kubuntu 15.04?  What's your python3.4 version?   `dpkg -l | grep python3.4`

**Comment by ivan** [comment]
And does upgrading all the dependencies fix anything?

```
pip3 install --user git+https://github.com/ludios/grab-site
```

**Comment by ivan** [comment]
The error suggests that `GrabberServerProtocol.onConnect` is not being called, at least for some clients.  This happened to me when I used trollius instead of asyncio (https://github.com/crossbario/autobahn-python/issues/426), but maybe it can happen for another reason as well.  Complicating matters is autobahn's habit of silently swallowing exceptions.

**Comment by ivan** [comment]
And what browser did you use to view the dashboard?  Maybe it's screwing up the websocket handshake.

**Comment by ethus3h** [comment]
Works in Chrome Version 46.0.2490.86 (64-bit) on OS X 10.11.

Yes, Kubuntu 15.04.

$ dpkg -l | grep python3.4
ii  libpython3.4:amd64                            3.4.3-3                                    amd64        Shared Python runtime library (version 3.4)
ii  libpython3.4-dev:amd64                        3.4.3-3                                    amd64        Header files and a static library for Python (v3.4)
ii  libpython3.4-minimal:amd64                    3.4.3-3                                    amd64        Minimal subset of the Python language (version 3.4)
ii  libpython3.4-stdlib:amd64                     3.4.3-3                                    amd64        Interactive high-level object-oriented language (standard library, version 3.4)
ii  python3.4                                     3.4.3-3                                    amd64        Interactive high-level object-oriented language (version 3.4)
ii  python3.4-dev                                 3.4.3-3                                    amd64        Header files and a static library for Python (v3.4)
ii  python3.4-minimal                             3.4.3-3                                    amd64        Minimal subset of the Python language (version 3.4)

Viewing in Firefox 42.0 on OS X 10.11.

**Comment by ethus3h** [comment]
Problem solved: it doesn't like being MITMed by Warcprox... #d'oh

**Comment by ivan** [comment]
Added a note in d80bde8c8cfbca2b10bde74e8dee1ffc4d02a36b
