### ISSUE TITLE
Problems Using phantom-js

### ISSUE THREAD

**Issue by dkl3** [ludios/grab-site#55]
Hi, I have a problem with using phantomjs with grabsite. I'll give you the output of me trying to use phantomjs with grab-site. Refer to Pastebin link:

http://pastebin.com/4SAqBn72

Someone help please? Thanks.

**Comment by ivan** [comment]
Please try

```
grab-site http://oldgamemags.tumblr.com/ --concurrency 3 --wpull-args="--phantomjs --phantomjs-scroll 0"
```

**Comment by dkl3** [comment]
http://pastebin.com/DBbnTh26 - I get this error

**Comment by ivan** [comment]
```
cd ~/
wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar -xf phantomjs-1.9.8-linux-x86_64.tar.bz2
~/.local/bin/grab-site http://oldgamemags.tumblr.com/ --concurrency 3 --wpull-args="--phantomjs --phantomjs-scroll 0 --phantomjs-exe=$HOME/phantomjs-1.9.8-linux-x86_64/bin/phantomjs"
```

(alternatively, set `PATH` to include that phantomjs bin/ directory)

If you're not on an x64 Linux, grab the right phantomjs 1.9.8 from https://bitbucket.org/ariya/phantomjs/downloads

**Comment by ivan** [comment]
Note that these tumblrs *can* be crawled completely without phantomjs (afaik); note how http://oldgamemags.tumblr.com/archive does link to everything, it's just got page styling hiding the content.

**Comment by dkl3** [comment]
Oh, sorry, I didn't know that.

**Comment by dkl3** [comment]
But thanks for the help, it worked. :)
