### ISSUE TITLE
Allow specifying a job ident

### ISSUE THREAD

**Issue by 12As** [ludios/grab-site#57]
In order to make job resumption, scripting and integration easier, it would be nice to be able to set the ident for a job.  There are three possible sources: an command line option, an environmental variable and an already existing file in the working directory once #56 is enabled.  Not sure what the order of precedence should be, but my initial inclination is

1. Existing ident file
2. Command line option
3. Environmental variable

**Comment by ivan** [comment]
I've added an `--id=` option in adb35ee4e3369158f8d85421b384f953b11273a6.

Note that resumption requires a lot more work (using the right warc name, not clobbering existing control files, reading an existing `DIR/id` file.)

I'll add an environment variable later when I figure out click's built-in support for env vars.
