### ISSUE TITLE
Add an icon

### ISSUE THREAD

**Issue by ivan** [ludios/grab-site#6]
`grab-site` needs an icon or icons to be used in the README, the dashboard favicon, and on sites like alternativeto.net.

Possible ideas: copy machines, bits being vacuumed, tangled webs, scriptoriums.  Something abstract, or perhaps a clever image might work.

**Comment by ethus3h** [comment]
An idea I had for an icon went into this pull request: https://github.com/ludios/grab-site/pull/21

**Comment by ivan** [comment]
Growing fond of http://www.dreamstime.com/royalty-free-stock-photography-xerox-machine-image27023377 via https://www.google.com/search?tbm=isch&q=copy%20machine%20clip%20art

**Comment by ivan** [comment]
`://` icon was added a few weeks ago
