### ISSUE TITLE
Document how to grab a website that requires login

### ISSUE THREAD

**Issue by ivan** [ludios/grab-site#63]
> Do you know if it there is a way to provide credentials for webistes that require login to download files? (Don't see any mention of it on the readme)

https://www.reddit.com/r/selfhosted/comments/3pg505/self_hosted_alternative_to_mirroring_sites/

**Comment by ivan** [comment]
Probably depends on #34

**Comment by ethus3h** [comment]
For basic HTTP/FTP authentication, wpull's --user and --password can be used.

**Comment by brandongalbraith** [comment]
If the site requires an application login/password, you can use the `--load-cookies` and `--save-cookies` [options in wpull](http://wpull.readthedocs.io/en/master/options.html).

```
wpull --save-cookies cookies.txt \
     --post-data 'user=foo&password=bar' \
     http://server.com/auth.php
```

**Comment by ivan** [comment]
https://github.com/ludios/grab-site#website-requiring-login--cookies
