### ISSUE TITLE
OS X 10.11: default US-ASCII codec breaks click

### ISSUE THREAD

**Issue by rwoodpecker** [ludios/grab-site#64]
I've just tried running grab-site on OSX (after having no problems on Linux) and regardless of what I input, for example grab-site and grab-site http://www.google.com I get the following:

```
Traceback (most recent call last):
  File "/Volumes/Macintosh HD/Users/user/Library/Python/3.4/bin/grab-site", line 4, in <module>
    main.main()
  File "/Volumes/Macintosh HD/Users/user/Library/Python/3.4/lib/python/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Volumes/Macintosh HD/Users/user/Library/Python/3.4/lib/python/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/Volumes/Macintosh HD/Users/user/Library/Python/3.4/lib/python/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: 'str' does not support the buffer interface
```

**Comment by ivan** [comment]
Thanks for the report.  Can you tell me what version of Python and click you have?

```
python3 --version
```

```
ls -l "/Volumes/Macintosh HD/Users/user/Library/Python/3.4/lib/python/site-packages" | grep -i click
```

**Comment by rwoodpecker** [comment]
Sure.

python3 --version
Python 3.4.3

drwxr-xr-x  20 user  staff   680B Dec 30 10:15 click/
drwxr-xr-x   8 user  staff   272B Dec 30 10:15 click-6.2.dist-info/

**Comment by ivan** [comment]
I have filed a click bug, but the click source suggests the real source of the problem might be a misconfigured locale on your system (Python believes it is 'ascii' instead of some UTF-8 variant).

What does this print?

```
locale -a; echo; python3 -c 'import codecs, locale; print(locale.getpreferredencoding()); print(codecs.lookup(locale.getpreferredencoding()).name)'
```

You might be able to make grab-site work by starting it with

```
LC_ALL=C.UTF-8 LANG=C.UTF-8 grab-site ...
```

or by adding

```
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```

to your `~/.bash_profile`.

**Comment by rwoodpecker** [comment]
It print's the following:

af_ZA
af_ZA.ISO8859-1
af_ZA.ISO8859-15
af_ZA.UTF-8
am_ET
am_ET.UTF-8
be_BY
be_BY.CP1131
be_BY.CP1251
be_BY.ISO8859-5
be_BY.UTF-8
bg_BG
bg_BG.CP1251
bg_BG.UTF-8
ca_ES
ca_ES.ISO8859-1
ca_ES.ISO8859-15
ca_ES.UTF-8
cs_CZ
cs_CZ.ISO8859-2
cs_CZ.UTF-8
da_DK
da_DK.ISO8859-1
da_DK.ISO8859-15
da_DK.UTF-8
de_AT
de_AT.ISO8859-1
de_AT.ISO8859-15
de_AT.UTF-8
de_CH
de_CH.ISO8859-1
de_CH.ISO8859-15
de_CH.UTF-8
de_DE
de_DE.ISO8859-1
de_DE.ISO8859-15
de_DE.UTF-8
el_GR
el_GR.ISO8859-7
el_GR.UTF-8
en_AU
en_AU.ISO8859-1
en_AU.ISO8859-15
en_AU.US-ASCII
en_AU.UTF-8
en_CA
en_CA.ISO8859-1
en_CA.ISO8859-15
en_CA.US-ASCII
en_CA.UTF-8
en_GB
en_GB.ISO8859-1
en_GB.ISO8859-15
en_GB.US-ASCII
en_GB.UTF-8
en_IE
en_IE.UTF-8
en_NZ
en_NZ.ISO8859-1
en_NZ.ISO8859-15
en_NZ.US-ASCII
en_NZ.UTF-8
en_US
en_US.ISO8859-1
en_US.ISO8859-15
en_US.US-ASCII
en_US.UTF-8
es_ES
es_ES.ISO8859-1
es_ES.ISO8859-15
es_ES.UTF-8
et_EE
et_EE.ISO8859-15
et_EE.UTF-8
eu_ES
eu_ES.ISO8859-1
eu_ES.ISO8859-15
eu_ES.UTF-8
fi_FI
fi_FI.ISO8859-1
fi_FI.ISO8859-15
fi_FI.UTF-8
fr_BE
fr_BE.ISO8859-1
fr_BE.ISO8859-15
fr_BE.UTF-8
fr_CA
fr_CA.ISO8859-1
fr_CA.ISO8859-15
fr_CA.UTF-8
fr_CH
fr_CH.ISO8859-1
fr_CH.ISO8859-15
fr_CH.UTF-8
fr_FR
fr_FR.ISO8859-1
fr_FR.ISO8859-15
fr_FR.UTF-8
he_IL
he_IL.UTF-8
hi_IN.ISCII-DEV
hr_HR
hr_HR.ISO8859-2
hr_HR.UTF-8
hu_HU
hu_HU.ISO8859-2
hu_HU.UTF-8
hy_AM
hy_AM.ARMSCII-8
hy_AM.UTF-8
is_IS
is_IS.ISO8859-1
is_IS.ISO8859-15
is_IS.UTF-8
it_CH
it_CH.ISO8859-1
it_CH.ISO8859-15
it_CH.UTF-8
it_IT
it_IT.ISO8859-1
it_IT.ISO8859-15
it_IT.UTF-8
ja_JP
ja_JP.eucJP
ja_JP.SJIS
ja_JP.UTF-8
kk_KZ
kk_KZ.PT154
kk_KZ.UTF-8
ko_KR
ko_KR.CP949
ko_KR.eucKR
ko_KR.UTF-8
lt_LT
lt_LT.ISO8859-13
lt_LT.ISO8859-4
lt_LT.UTF-8
nl_BE
nl_BE.ISO8859-1
nl_BE.ISO8859-15
nl_BE.UTF-8
nl_NL
nl_NL.ISO8859-1
nl_NL.ISO8859-15
nl_NL.UTF-8
no_NO
no_NO.ISO8859-1
no_NO.ISO8859-15
no_NO.UTF-8
pl_PL
pl_PL.ISO8859-2
pl_PL.UTF-8
pt_BR
pt_BR.ISO8859-1
pt_BR.UTF-8
pt_PT
pt_PT.ISO8859-1
pt_PT.ISO8859-15
pt_PT.UTF-8
ro_RO
ro_RO.ISO8859-2
ro_RO.UTF-8
ru_RU
ru_RU.CP1251
ru_RU.CP866
ru_RU.ISO8859-5
ru_RU.KOI8-R
ru_RU.UTF-8
sk_SK
sk_SK.ISO8859-2
sk_SK.UTF-8
sl_SI
sl_SI.ISO8859-2
sl_SI.UTF-8
sr_YU
sr_YU.ISO8859-2
sr_YU.ISO8859-5
sr_YU.UTF-8
sv_SE
sv_SE.ISO8859-1
sv_SE.ISO8859-15
sv_SE.UTF-8
tr_TR
tr_TR.ISO8859-9
tr_TR.UTF-8
uk_UA
uk_UA.ISO8859-5
uk_UA.KOI8-U
uk_UA.UTF-8
zh_CN
zh_CN.eucCN
zh_CN.GB18030
zh_CN.GB2312
zh_CN.GBK
zh_CN.UTF-8
zh_HK
zh_HK.Big5HKSCS
zh_HK.UTF-8
zh_TW
zh_TW.Big5
zh_TW.UTF-8
C
POSIX

US-ASCII
ascii

I tried both of those but it appears to have the same result as before unfortunately.

**Comment by ivan** [comment]
It looks like you don't have a C.UTF-8, so please try

```
LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 grab-site ...
```

**Comment by rwoodpecker** [comment]
That works. Thanks!

**Comment by ivan** [comment]
I probably need to add something about this to the README for OS X users, so I'm curious:

Which OS X version and which Terminal were you using?

If Terminal.app, did you have "Set locale environment variables" checked?  (See the screenshot on http://blog.remibergsma.com/2012/07/10/setting-locales-correctly-on-mac-osx-terminal-application/)

It might need to be unchecked, or alternatively checked with the right encoding set.

**Comment by ivan** [comment]
And were you running inside or outside a tmux?

**Comment by rwoodpecker** [comment]
I'm running latest OSX El Capitan.

I mainly use iTerm2 but also tried it in the default terminal.app to no avail. 'set locale environment variables' is/was unticked in both terminals and encoding shows to be Unicode UTF-8 in both terminals settings..

This was all done outside of tmux.

**Comment by ivan** [comment]
One more question :smile:, what does this print?

```
locale
```

I admit I'm stumped, because OS X should be using a UTF-8 locale by default, and it worked fine in 10.11 when I tested it.  Something has gone terribly wrong somewhere, either in the system configuration, in a shell `profile` or `bashrc` (either system-wide or per-user), some other script sourced by `.bash_profile`, or perhaps in the Python install (an auto-loaded module screwing with the environment?)

**Comment by ivan** [comment]
Note to self http://bugs.python.org/issue23374#msg235203

**Comment by rwoodpecker** [comment]
Without any of those exports... woah

LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

**Comment by ivan** [comment]
OK, I have played around with OS X 10.11 some more and it looks like you want "Set locale environment variables on startup" **checked** in Terminal.app -> Profiles -> Advanced.  That was the default here on a clean OS X 10.11 install.  Text encoding should be Unicode (UTF-8).  Not sure what the iTerm 2 equivalent of these settings are.

**Comment by rwoodpecker** [comment]
That's very useful.. I have no idea why that wasn't ticked. 

I found it under iTerm2 it's Preferences -> Profiles -> Terminal -> set locale variables automatically

Thanks for your assistance.
