### ISSUE TITLE
Crawl with phantomjs doesn't exit after archiving a twitter hashtag page

### ISSUE THREAD

**Issue by dkl3** [ludios/grab-site#71]
Hi, I've been trying to download a Twitter hashtag page with grab-site using phantom-js. Everything downloads fine, except it refuses to terminate near the end.

This is the command I used:

grab-site https://twitter.com/hashtag/ModTalkLeaks/ --concurrency 3 --wpull-args="--phantomjs --phantomjs-scroll 0 --phantomjs-exe=$HOME/phantomjs-1.9.8-linux-x86_64/bin/phantomjs"

Pics (in order):

http://i.imgur.com/aljK3tO.png - Downloads fine...
http://i.imgur.com/6KgeDgc.png - Still okay...
http://i.imgur.com/Fb0klGR.png - Stops here.
http://i.imgur.com/wPNE0WQ.png - Had to press Ctrl + C on the command prompt...
http://i.imgur.com/qlEcvMk.png - And only enough times until it finally stops.

I don't know how else to show it other than taking screencaps and showing you the command I used at the very start. Whoever is willing to help should probably try the same command that I did.

**Comment by ivan** [comment]
I don't really have any knowledge of how wpull's phantomjs support works, the the phantomjs version it requires is hopelessly outdated, and I never use it, and for these reasons I decided to not document phantomjs support in grab-site.

You might want to file this upstream on wpull.

https://webrecorder.io/ would probably do a much better job of archiving infinite-scroll twitter pages.  It also has a button to autoscroll the site.

**Comment by dkl3** [comment]
Oh, that's so cool! Thanks ivan!

I guess we should close this issue now? But one last thing, what will be the alternative to phantom-js in wpull/grab-site then?

**Comment by ivan** [comment]
I haven't tried the alternatives but some kind of Chrome-based crawling (e.g. https://github.com/internetarchive/umbra or https://github.com/nlevitt/brozzler) would be worth looking into.  I don't know if those are already programmed to autoscroll twitter.

**Comment by ivan** [comment]
FWIW, making major improvements to grab-site is nowhere near the top of my list of stuff-to-do.  It's a miracle chfoo gave us a useful crawler and my goals with grab-site were to get the ArchiveBot dashboard and ignores functionality into a program that anyone with a Linux machine could run.  Users with unsolved archiving needs may need to pick up Python programming and make the relevant fixes, or start work on replacement infrastructure (it takes a while), etc.
