### ISSUE TITLE
Allow crawling localhost and LAN IPs if crawl starts on such a domain

### ISSUE THREAD

**Issue by ivan** [ludios/grab-site#77]
This tripped me up and it took me a while to figure out why my crawl was finishing with 0 responses

**Comment by 12As** [comment]
In case you didn't notice, the ignore sets contain ignores for various local addresses and private addresses.  A long term fix would probably be to implement https://github.com/ludios/grab-site/issues/72 for those ignores.

**Comment by ivan** [comment]
Ah, yes, using #72 to fix this is a good point

**Comment by ivan** [comment]
Fixed in 2d7222cc5fb74eef583180a0f6af31c43dab0cc5 by removing this ineffective protection
