### ISSUE TITLE
IndexError: list index out of range with --1 option

### ISSUE THREAD

**Issue by ethus3h** [ludios/grab-site#8]
$ grab-site --1 https://archive.org/post/1033012/constant-removal-of-isis-videos-and-publications-from-internet-archive
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: list index out of range
mkdir: illegal option -- 2
usage: mkdir [-pv] [-m mode] directory ...
$

**Comment by ethus3h** [comment]
This is a result of not putting the --1 option after the URL.

**Comment by ivan** [comment]
https://github.com/ludios/grab-site/issues/9
