### ISSUE TITLE
Enhancement idea: easier multi-URL crawl starting and handling of aggressive extraction

### ISSUE THREAD

**Issue by ethus3h** [ludios/grab-site#82]
**Suggestion 1**: It would be nice to have an option such as:

--traverse-parents

that would cause link selection for crawling http://example.com/foo/bar/ to behave as for crawling http://example.com/, and 

--traverse-parents=1

that would cause it to behave as for crawling http://example.com/foo/

**Suggestion 2**: I suggest an option such as:

--allow-seed-expansion

that when enabled would allow something like:

```
grab-site --allow-seed-expansion (http|https)://(www|ww[2-5]|cdn|blog).example.(com|co.uk)/
```

and would have the effect of running:

```
grab-site -i foo.txt
```
where foo.txt contains:
```
http://www.example.com/
http://ww2.example.com/
http://ww3.example.com/
http://ww4.example.com/
http://ww5.example.com/
http://cdn.example.com/
http://blog.example.com/
http://www.example.co.uk/
http://ww2.example.co.uk/
http://ww3.example.co.uk/
http://ww4.example.co.uk/
http://ww5.example.co.uk/
http://cdn.example.co.uk/
http://blog.example.co.uk/
https://www.example.com/
https://ww2.example.com/
https://ww3.example.com/
https://ww4.example.com/
https://ww5.example.com/
https://cdn.example.com/
https://blog.example.com/
https://www.example.co.uk/
https://ww2.example.co.uk/
https://ww3.example.co.uk/
https://ww4.example.co.uk/
https://ww5.example.co.uk/
https://cdn.example.co.uk/
https://blog.example.co.uk/
```

**Suggestion 3**: It would be nice to have an option such as:

--aggressive-url-extraction

that when enabled would extract:

- URLs that are in plain text (not hyperlinked)
- Parent directories, and their possible index etc. documents
- Different protocols
- Alternate capitalizations
- Alternate extensions
- Variations of HTML entities / URL encoded characters
- Variations with and without Unicode characters truncated
- Variations with and without control characters removed
- URLs found in incorrect HTML
- Malformed URLs

E.g. if the document contains '<a href="http://example.org/foo/bar/baz.html">blah</a> http://blog.fi/foo/bar/baz la.ws htttp://io.eu/foo/bar/baz.htm ./examp%02%25😹.jpg <img=./ex.aif" />/img>' it would consider it as linking to:

```
(http|https|ftp|news|nntp|onion|gopher)://(|.(www|ww|blog|cms|admin|search|mail|cpanel|pma|log|logs|support|help|helpdesk|en|cn|fr|gb|us|uk|wp|ww[0-100]|status|home|web|ww-[0-100]|alt|mirror|backup|bbs|ns[0-9]|ns|pkg|pkgs|packages|old|site|data|tmp|temp|forum|forums|wiki|wikis|alternate|backup|home|login|openid|open-id))(la.ws|(example.org|blog.fi|io.eu)(|foo|tmp|temp|data|site|forum|wiki|d|s|home|log|logs|mail|wp-content(|/uploads)|wp-admin)(|/bar)(|/(|index|Index|INDEX|sitemap|Sitemap|SITEMAP|home|Home|HOME|main|Main|MAIN|robots|Robots|ROBOTS|humans|Humans|HUMANS|hackers|Hackers|HACKERS|jobs|Jobs|JOBS|blog|Blog|BLOG)(|.(|htm|html|php|asp|aspx|shtml|xml|woa|cfm|stm|stml|xhtml|xml.gz|json|txt|text|Htm|Html|Php|Asp|Aspx|Shtml|Xml|Woa|Cfm|Stm|Stml|Xhtm|Xml.gz|Xml.Gz|xml.Gz|Txt|TEXT|XML.Gz|Json|HTM|HTML|PHP|ASP|ASPX|SHTML|XML|wWOA|CFM|STM|STML|XHTML|XML.GZ|JSON|TXT|TEXT)))
./ex((|amp|&|%26|%2526|&amp;|&amp|%26amp|%26amp%3B|&amp%3B|%26amp;)(|%02)(%25|%2525)(|😹.(jpg|Jpg|JPG|jpeg|Jpeg|JPEG|jfif|Jfif|JFIF|png|Png|PNG|bmp|Bmp|BMP|gif|Gif|GIF))|(|.(aif|Aif|AIF|aiff|Aiff|AIFF|mp3|Mp3|MP3|wav|Wav|WAV)))
```
(This feature would infer URLs in a similar manner for the seed URL.)

**Comment by ethus3h** [comment]
(The example for suggestion 3 was supposed to be:

```
<a href="http://example.org/foo/bar/baz.html">blah</a> http://blog.fi/foo/bar/baz la.ws htttp://io.eu/foo/bar/baz.htm <img=./examp%02%25😹.jpg">/img>
```
but got mangled by Markdown or GitHub, apparently.)

**Comment by ivan** [comment]
You can use shell argument expansion to do Suggestion 2 with 

```
grab-site {http,https}://{www,ww{2..5},cdn,blog}.example.{com,co.uk}/
```

or

```
echo {http,https}://{www,ww{2..5},cdn,blog}.example.{com,co.uk}/ | sed 's/ /\n/g'
```

to test it out

**Comment by ivan** [comment]
I think you can do Suggestion 1 by starting a crawl with

```
grab-site http://example.com/foo/bar/ http://example.com/
```

**Comment by ethus3h** [comment]
Oh, it allows multiple arguments passed on the command line?
_A whole new world has opened up for me!_
Sweet, thanks!

**Comment by ivan** [comment]
Pretty sure wpull already does "URLs that are in plain text (not hyperlinked)".

"Alternate capitalizations" is not really feasible given the number of combinations.  Some of the others would also expand to a very number of URLs.  I find that crawls already find way too many URLs, so I'm not sure about extracting even more links (of which 99%+? would be useless).

If link extraction does not work properly on some site, it would probably be helpful to work more like a web browser in most cases, since web authors test their sites in browsers.  It would be useful to know specific sites on which link extraction is currently buggy.

**Comment by ivan** [comment]
"Parent directories" is something I've wanted for a while, but I'm not sure about enabling it by default because there are websites with a very deep directory structure like cdn.blah.com/a/ab/c/1/2/3/4/image.jpg

**Comment by ethus3h** [comment]
I wouldn't consider the --aggressive-link-extraction option I proposed suitable as a default, probably.

Regarding the enormous number of URLs that could result, I see that as more of a feature than a bug, but I think that's just a matter of perspective. That option would presumably be unsuitable for a large Web site.

For alternate capitalisations, I'm referring specifically to lowercase, Initial-Letters-Of-Words-Capitalized, and ALL-UPPERCASE, because I have seen confusion between those forms cause Web sites to be crawled incompletely.

**Comment by ethus3h** [comment]
Timely: 
```
balrog	wpull should have an added feature -- trying raw paths

so like if something links to www.somesite.com/blah/file.html it will try /blah
	[06:10]
```

**Comment by ivan** [comment]
re: suggestions 1 and 2, I've added a note to the README about multiple URL arguments.

> For alternate capitalisations, I'm referring specifically to lowercase, Initial-Letters-Of-Words-Capitalized, and ALL-UPPERCASE, because I have seen confusion between those forms cause Web sites to be crawled incompletely.

And try every combination given many path components?  Or modify just the last component?

For more-aggressive link extraction, I would recommend filing bugs on wpull with example sites where they would be useful.  The crawling of parent directories seems like the most useful suggestion.  But in cases where even a browser can't follow the links on the website properly, it seems strange to expect a crawler to get it right by doing things like automatic re-casing.  That should probably somehow be done on a per-site basis with the user supplying the correct links.  Perhaps wpull could have a `transform_url` hook that allows you to turn one extracted URL into multiple URLs?

Closing since I don't plan to take action on this, but comments are welcome.

**Comment by ethus3h** [comment]
Ok, cool, thanks! I'll probably make a patch or something to do this eventually. (I'd eventually like to get an app working that can archive a variety of sources automatically, e.g. local files, gopher, torrents, youtube sites, etc., so I might just end up doing this in that)
