### ISSUE TITLE
Allow multiple locations and protocols in gs-server environmental variables

### ISSUE THREAD

**Issue by 12As** [ludios/grab-site#86]
Currently, there is issue https://github.com/ludios/grab-site/issues/83 and I am close to complete Unix domain socket support between grabbers and gs-server.  Both raise issues on how to specify where to listen/connect.

For the grabbers, I think changing the syntax of the `GRAB_SITE_HOST` variable to allow `scheme://address` where scheme is one of `ws` or `wss` or `unix` or `udss` for websocket, ssl websocket, unix socket and ssl unix socket, respectively.  

However, I'm not sure what the proper course is on the variables for gs-server.  For instance, how would one specify to listen on SSL on `0.0.0.0` but non-ssl on `/tmp/gs-server.socket`?  Or, ssl on `10.0.0.1` but non-ssl on `127.0.0.1`?

**Comment by ivan** [comment]
How about

```
GRAB_SITE_TCP_INTERFACE
GRAB_SITE_TCP_PORT
GRAB_SITE_SSL_INTERFACE
GRAB_SITE_SSL_PORT
```

with support for the old variables as well?  (`GRAB_SITE_INTERFACE` and `GRAB_SITE_PORT` applying only to TCP.)

**Comment by ivan** [comment]
Why are you implementing Unix domain socket support?  Some people do it for a slight optimization, but the TCP stack on Linux has very little overhead, especially for something as low-bandwidth as grab-site.  Some do it for user-based security, but does that apply here to grab-site where gs-server doesn't really have any security in the first place?

**Comment by ivan** [comment]
An alternative to those environmental variables might be to switch gs-server to using click for command-line arguments and support syntax like http://twistedmatrix.com/documents/8.1.0/api/twisted.application.strports.html for listening on things.

**Comment by 12As** [comment]
I like your initial idea, keeps it simple for the user and the server only needs to figure out the combinations once.  The click + twisted syntax seems a bit overkill.

As for your question, I didn't really set out to support Unix sockets.  I was trying to learn more about sockets in general and how they work in Python.  Some time during that I bumped into the concept of them.  Regardless, after going down the rabbit hole, they worked in grab-site.  If you view it as feature creep or otherwise unnecessary, no problem.  They already served their purpose.
