### ISSUE TITLE
Problem using -i option again

### ISSUE THREAD

**Issue by dkl3** [ludios/grab-site#89]
Try any text file in this instance, and you'll get this error:

http://pastebin.com/kW6jwX0J

I don't have much else to say. There seems to be a url on every line--I'm sure of it.

**Comment by dkl3** [comment]
Also, this is the list of urls I am using for this: http://pastebin.com/xyzAJi4Q

**Comment by ivan** [comment]
I patched `/home/grab/.local/lib/python3.4/site-packages/wpull/url.py:normalize_hostname` to `print(repr(` the URL first, and the one it crashes on is:

```
'hasthelargehadroncolliderdestr...'
```

Your URL list seems to be corrupted with a lot of `...` elisions.

**Comment by ivan** [comment]
A hostname in a URL can't contain consecutive dots, so if you remove those URLs, it should work.

**Comment by dkl3** [comment]
Well, then it was all my fault. We can close this now.
